INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('1', '01', '1', 'um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('2', '02', '2', 'dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('3', '03', '3', 'três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('4', '04', '4', 'quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('5', '05', '5', 'cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('6', '06', '6', 'seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('7', '07', '7', 'sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('8', '08', '8', 'oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('9', '09', '9', 'nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('10', '10', '10', 'dez');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('11', '11', '11', 'onze');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('12', '12', '12', 'doze');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('13', '13', '13', 'treze');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('14', '14', '14', 'quatorze');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('15', '15', '15', 'quinze');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('16', '16', '16', 'dezesseis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('17', '17', '17', 'dezessete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('18', '18', '18', 'dezoito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('19', '19', '19', 'dezenove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('20', '20', '20', 'vinte');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('21', '21', '21', 'vinte e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('22', '22', '22', 'vinte e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('23', '23', '23', 'vinte e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('24', '24', '24', 'vinte e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('25', '25', '25', 'vinte e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('26', '26', '26', 'vinte e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('27', '27', '27', 'vinte e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('28', '28', '28', 'vinte e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('29', '29', '29', 'vinte e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('30', '30', '30', 'trinta');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('31', '31', '31', 'trinta e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('32', '32', '32', 'trinta e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('33', '33', '33', 'trinta e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('34', '34', '34', 'trinta e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('35', '35', '35', 'trinta e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('36', '36', '36', 'trinta e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('37', '37', '37', 'trinta e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('38', '38', '38', 'trinta e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('39', '39', '39', 'trinta e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('40', '40', '40', 'quarenta');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('41', '41', '41', 'quarenta e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('42', '42', '42', 'quarenta e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('43', '43', '43', 'quarenta e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('44', '44', '44', 'quarenta e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('45', '45', '45', 'quarenta e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('46', '46', '46', 'quarenta e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('47', '47', '47', 'quarenta e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('48', '48', '48', 'quarenta e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('49', '49', '49', 'quarenta e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('50', '50', '50', 'cinquenta');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('51', '51', '51', 'cinquenta e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('52', '52', '52', 'cinquenta e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('53', '53', '53', 'cinquenta e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('54', '54', '54', 'cinquenta e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('55', '55', '55', 'cinquenta e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('56', '56', '56', 'cinquenta e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('57', '57', '57', 'cinquenta e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('58', '58', '58', 'cinquenta e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('59', '59', '59', 'cinquenta e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('60', '60', '60', 'sessenta');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('61', '61', '61', 'sessenta e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('62', '62', '62', 'sessenta e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('63', '63', '63', 'sessenta e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('64', '64', '64', 'sessenta e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('65', '65', '65', 'sessenta e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('66', '66', '66', 'sessenta e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('67', '67', '67', 'sessenta e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('68', '68', '68', 'sessenta e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('69', '69', '69', 'sessenta e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('70', '70', '70', 'setenta');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('71', '71', '71', 'setenta e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('72', '72', '72', 'setenta e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('73', '73', '73', 'setenta e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('74', '74', '74', 'setenta e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('75', '75', '75', 'setenta e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('76', '76', '76', 'setenta e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('77', '77', '77', 'setenta e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('78', '78', '78', 'setenta e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('79', '79', '79', 'setenta e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('80', '80', '80', 'oitenta');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('81', '81', '81', 'oitenta e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('82', '82', '82', 'oitenta e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('83', '83', '83', 'oitenta e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('84', '84', '84', 'oitenta e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('85', '85', '85', 'oitenta e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('86', '86', '86', 'oitenta e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('87', '87', '87', 'oitenta e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('88', '88', '88', 'oitenta e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('89', '89', '89', 'oitenta e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('90', '90', '90', 'noventa');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('91', '91', '91', 'noventa e um');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('92', '92', '92', 'noventa e dois');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('93', '93', '93', 'noventa e três');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('94', '94', '94', 'noventa e quatro');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('95', '95', '95', 'noventa e cinco');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('96', '96', '96', 'noventa e seis');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('97', '97', '97', 'noventa e sete');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('98', '98', '98', 'noventa e oito');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('99', '99', '99', 'noventa e nove');
INSERT INTO `project_lotto_db`.`numero` (`idnumero`, `descricao`, `num`, `extenso`) VALUES ('100', '100', '100', 'cem');
